config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions',
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  # 顧客
  root to: "customer/plans#index"
  get "/about" => "customer/homes#about"
  get "/photographs" => "customer/homes#index"

  scope module: :customer do
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get "unsubsclibe"
        patch "withdraw"
      end
    end

    resources :plans, only: [:index, :show, :create] do
      collection do
        get "flow"
        get "bridal"
        get "seizinshiki"
        get "maternity"
        get "child"
        get "trip"
        get "couple"
        get "shichigosan"
        get "friend"
      end
    end

    resources :reserves, except: [:update, :destroy, :edit] do
      collection do
        post "confirm"
        post "back"
        get "complete"
      end
    end

    resources :contacts do
      collection do
        post "confirm"
        post "back"
        get "complete"
      end
    end

    resources :calenders, only: [:index]

    resources :reviews
  end

  # 管理者
  namespace :admin do
    resources :homes
    resources :tags, except: [:show, :new]
    resources :customers, except: [:new, :create, :destroy]
    resources :reserves, only: [:index, :show]
    resources :contacts, except: [:show]
    resources :calenders, except: [:show, :destroy]
    resources :reviews, only: [:index, :destroy]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reserves
  has_many :contacts
  has_many :reviews

  # バリデーション
  with_options presence: true do
    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :post_cord, presence: true
    validates :address, presence: true
  end

  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :phone_number, presence: true, numericality: { only_integer: true }
  validates :email, presence: true, uniqueness: true

end

app/models/reserve.rb
class Reserve < ApplicationRecord

  belongs_to :customer, optional: true

  # enum設定
  enum plan_name: {
    bridal: 0, seizinshiki: 1, maternity: 2,
    child: 3, trip: 4, couple: 5, shichigosan: 6, friend: 7,
  }

  # バリデーション
  with_options presence: true do
    validates :plan_name
    validates :count
    validates :reserve_day
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:success] = "登録情報を更新しました"
      redirect_to "/admin/customers/#{@customer.id}"
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_cord, :address, :phone_number, :is_deleted, :email)
  end
end

app/controllers/admin/reserves_controller.rb
class Admin::ReservesController < ApplicationController
  
  def index
    @reserves = Reserve.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  private

  def reserve_params
    params.require(:reserve).permit(:customer_id, :count, :reserve_day, :plan_name)
  end
  
end

app/controllers/customer/calenders_controller.rb
class Customer::CalendersController < ApplicationController
  before_action :set_beginning_of_week

  def index
    @calenders = Calender.all
  end

  private

  def calender_parameter
    params.require(:calender).permit(:title, :start_at)
  end

  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end
  
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/contacts_controller.rb
class Customer::ContactsController < ApplicationController
  
  def index
    @contacts = Contact.all.order(created_at: :desc).page(params[:page]).per(15)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save(validate: false)
      ContactMailer.send_when_customer_contact(@contact).deliver_now
      redirect_to contacts_path, notice: "お問い合わせを送信しました。"
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:customer_id, :name, :email, :title, :detail, :title_reply, :detail_reply)
  end
  
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
    @customer = current_customer
  end

  def unsubclibe
    @customer = current_customer
  end

  def withdraw
    @customer = current_customer
    @current_customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_cord, :address, :phone_number, :is_deleted, :email)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  
  def index
    @photos = Home.all.order(created_at: :desc).page(params[:page]).per(9)
    @photos_all = Home.all
    @tags = Tag.all
  end

  private

  def photo_params
    params.require(:home).permit(:image, :tag_id)
  end
  
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/plans_controller.rb
class Customer::PlansController < ApplicationController
  
  def index
    @plans = Plan.all
  end
  
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      flash[:notice] = "登録情報を更新しました"
      redirect_to customers_path
    else
      render :edit
    end
  end

  # 退会処理
  def unsubclibe
    @customer = current_customer
  end

  # 退会処理（論理処理）
  def withdraw
    @customer = current_customer
    @current_customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_cord, :address, :phone_number, :is_deleted, :email)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_cord, :address, :phone_number])
  end

  private

  # ログイン後はマイページを表示
  def after_sign_up_path_for(resource)
    customers_path
  end
end

app/controllers/customer/reserves_controller.rb
class Customer::ReservesController < ApplicationController
  
  def index
    @reserves = Reserve.where(customer_id: current_customer.id).order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
    @reserve = Reserve.new
    @reserve_price = 8000
  end

  def confirm
    @reserve = Reserve.new(reserve_params)
    @reserve.customer_id = current_customer.id
    @reserve_price = 8000
    render :new if @reserve.invalid?
  end

  def create
    @reserve = Reserve.new(reserve_params)
    render :new and return if params[:back] || !@reserve.save
    if @reserve.save
      redirect_to complete_reserves_path
      ReserveMailer.send_when_customer_reserve(@reserve).deliver_now
    else
      render :new
    end
  end

  private

  def reserve_params
    params.require(:reserve).permit(:customer_id, :count, :reserve_day, :plan_name)
  end
  
end

app/controllers/customer/reviews_controller.rb
class Customer::ReviewsController < ApplicationController

  def index
    @reviews = Review.all.order(created_at: :desc).page(params[:page]).per(10)
    @reviews_all = Review.all
  end

  def create
    @review = Review.new(review_params)
    @review.score = Language.get_data(review_params[:contents])
    @review.customer_id = current_customer.id
    if @review.save
      redirect_to reviews_path, notice: "口コミを記載しました。"
    else
      render "new"
    end
  end

  def new
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to reviews_path, notice: "口コミを更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path, notice: "口コミを削除しました。"
  end

  private

  def review_params
    params.require(:review).permit(:title, :evaluation, :contents, :customer_id)
  end

end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :customer_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected

  # 退会処理後にログイン時は、新規登録画面に遷移
  def customer_state
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted? == true)
        redirect_to new_customer_registration_path
      end
    end
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/reserves_helper.rb
module Admin::ReservesHelper
end

app/helpers/customer/calenders_helper.rb
module Customer::CalendersHelper
end

app/views/customer/reserves/complete.html.erb
<div class="container mt-5 mb-5 complete">
  
  <div class="col d-flex align-items-center justify-content-center text-center" style="font-size: 30px;">
      ご依頼ありがとうございました。<br>
      後ほど、依頼内容についてご連絡致します。
  </div>
  <div class="text-center top-back">
    <%= button_to "トップページに戻る", root_path, method: :get, class: "btn btn-sm btn-dark text-center"%>
  </div>
</div>

app/views/customer/reserves/confirm.html.erb
<div class="container mt-5 mb-5 reserve-confirm">

  <h2>依頼情報確認</h2>
  <div class="row mt-3">
    <div class="col-8">

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>撮影希望日</th>
            <th>撮影シーン</th>
            <th>撮影人数</th>
            <th>金額</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @reserve.reserve_day.strftime('%Y年%m月%d日') %></td>
            <td><%= @reserve.plan_name_i18n %></td>
            <td><%= @reserve.count %></td>
            <td><%= @reserve_price %> 円</td>
          </tr>
        </tbody>
      </table>

      <%= form_with model: @reserve, url: reserves_path, method: :post, local: true do |f| %>
        <%= f.hidden_field :customer_id, value: current_customer.id %>
        <%= f.hidden_field :reserve_day, value: @reserve.reserve_day %>
        <%= f.hidden_field :plan_name, value: @reserve.plan_name %>
        <%= f.hidden_field :count, value: @reserve.count %>
        <div class="text-center mt-5">
          <%= f.submit "依頼を確定する", class: "btn btn-sm btn-dark" %>
        </div>
        <div class="text-center mt-5">
          <%= f.submit "入力画面に戻る", name: :back, class: "btn btn-sm btn-dark" %>
        </div>
      <% end %>

    </div>
  </div>

</div>

app/views/customer/reserves/index.html.erb
<div class="container mt-5 mb-5 reserves-index">

  <h2 class="text title-text">予約履歴一覧</h2>


  <% if @reserves.exists? %>
    <div class="col mt-5">
      
      <table class="table table-bordered table-hover">
        <thead class="table-active text">
          <tr>
            <th>予約受付日</th>
            <th>撮影希望日</th>
            <th>撮影シーン</th>
            <th>撮影人数</th>
          </tr>
        </thead>
        <tbody>
          <% @reserves.each do |reserve| %>
            <tr class="light-text">
              <td><%= reserve.created_at.strftime('%Y年%m月%d日 %H時%M分') %></td>
              <td><%= reserve.reserve_day.strftime('%Y年%m月%d日') %></td>
              <td><%= reserve.plan_name_i18n %></td>
              <td><%= reserve.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <div class="pagination">
        <%= paginate @reserves %>
      </div>
      
    </div>
  
  <% else %>
    <div class="text-center">
      <h2>※注文履歴がありません</h2>
    </div>
  <% end %>

</div>

app/views/customer/reserves/new.html.erb
<div class="container mt-5 mb-5 reserve-new">
  
    <h2>依頼情報入力</h2>

    <div class="reserve-new">
      
      <div class="validates">
        <% if @reserve.errors.any? %>
          <%= @reserve.errors.count %> 件の入力ミスがあります。
          <% @reserve.errors.full_messages.each do |message| %><br>
            ・<%= message %>
          <% end %>
        <% end %>
      </div>
      
      <%= form_with model: @reserve, url: confirm_reserves_path, local:true do |f| %>
        <table class="reserve">
          <tr>
            <th>氏名</th>
            <td>
              <%= current_customer.last_name %>
              <%= current_customer.first_name %>
            </td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td>
              <%= current_customer.last_name_kana %>
              <%= current_customer.first_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= current_customer.post_cord %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= current_customer.address %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= current_customer.phone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= current_customer.email %></td>
          </tr>
          <tr>
            <th>希望プラン</th>
            <td><%= f.select :plan_name, Reserve.plan_names.keys.map {|k| [I18n.t("enums.reserve.plan_name.#{k}"), k]}, :prompt => "選択してください" %></td>
          </tr>
          <tr>
            <th>撮影人数</th>
            <td><%= f.select :count, [[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10]], :prompt => "人数を選択してください" %>　※例) お友達2人と撮影希望⇨２人</td>
          </tr>
          <tr>
            <th>撮影希望日</th>
            <td><%= f.date_field :reserve_day %></td>
          </tr>
          <tr>
            <th>金額</th>
            <td>8000 円</td>
          </tr>
          <tr>
            <th><%= f.hidden_field :customer_id, value: current_customer.id %></th>
            <td><%= f.submit '確認画面に進む',class: "btn btn-sm btn-dark mt-3" %></td>
          </tr>
          <tr>
            <th></th>
            <td>※まだ確定ではありません</td>
          </tr>
        </table>
      <% end %>
         
    </div>

</div>