config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions',
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  # 顧客
  root to: "customer/plans#index"
  get "/about" => "customer/homes#about"
  get "/photographs" => "customer/homes#index"

  scope module: :customer do
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get "unsubsclibe"
        patch "withdraw"
      end
    end

    resources :plans, only: [:index, :show, :create] do
      collection do
        get "flow"
        get "bridal"
        get "seizinshiki"
        get "maternity"
        get "child"
        get "trip"
        get "couple"
        get "shichigosan"
        get "friend"
      end
    end

    resources :reserves, except: [:update, :destroy, :edit] do
      collection do
        post "confirm"
        post "back"
        get "complete"
      end
    end

    resources :contacts do
      collection do
        post "confirm"
        post "back"
        get "complete"
      end
    end

    resources :calenders, only: [:index]

    resources :reviews
  end

  # 管理者
  namespace :admin do
    resources :homes
    resources :tags, except: [:show, :new]
    resources :customers, except: [:new, :create, :destroy]
    resources :reserves, only: [:index, :show]
    resources :contacts, except: [:show]
    resources :calenders, except: [:show, :destroy]
    resources :reviews, only: [:index, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # バリデーション
  validates :email, presence: true, uniqueness: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calender.rb
class Calender < ApplicationRecord

  # バリデーション
  validates :start_time, presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord
  
  belongs_to :customers, optional: true

  # バリデーション
  with_options presence: true do
    validates :title
    validates :detail
    validates :title_reply
    validates :detail_reply
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reserves
  has_many :contacts
  has_many :reviews

  # バリデーション
  with_options presence: true do
    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :post_cord, presence: true
    validates :address, presence: true
  end

  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :phone_number, presence: true, numericality: { only_integer: true }
  validates :email, presence: true, uniqueness: true

end

app/models/home.rb
class Home < ApplicationRecord

  attachment :image

  belongs_to :tag

  # バリデーション
  with_options presence: true do
    validates :tag_id
    validates :image
  end

end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/reserve.rb
class Reserve < ApplicationRecord

  belongs_to :customer, optional: true

  # enum設定
  enum plan_name: {
    bridal: 0, seizinshiki: 1, maternity: 2,
    child: 3, trip: 4, couple: 5, shichigosan: 6, friend: 7,
  }

  # バリデーション
  with_options presence: true do
    validates :plan_name
    validates :count
    validates :reserve_day
  end

end

app/models/review.rb
class Review < ApplicationRecord
  
  belongs_to :customers, optional: true

  # enum設定
  enum title: {
    bridal: 0, seizinshiki: 1, maternity: 2,
    child: 3, trip: 4, couple: 5, shichigosan: 6, friend: 7,
  }

  # バリデーション
  with_options presence: true do
    validates :title
    validates :evaluation
    validates :contents
  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :homes

  # バリデーション
  validates :name, presence: true

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def index
    @photos = Home.all.order(created_at: :desc).page(params[:page]).per(9)
    @photos_all = Home.all
  end

  def show
    @photo = Home.find(params[:id])
  end

  def new
    @photo = Home.new
  end

  def create
    @photo = Home.new(home_params)
    if @photo.save
      redirect_to admin_home_path(@photo.id), notice: "写真を新規追加しました。"
    else
      render :new
    end
  end

  def edit
    @photo = Home.find(params[:id])
  end

  def update
    @photo = Home.find(params[:id])
    if @photo.update(home_params)
      redirect_to admin_home_path(@photo.id), notice: "写真情報を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @photo = Home.find(params[:id])
    @photo.destroy
    redirect_to admin_homes_path, notice: "写真を削除しました"
  end

  private

  def home_params
    params.require(:home).permit(:image, :tag_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  
  def index
    @photos = Home.all.order(created_at: :desc).page(params[:page]).per(9)
    @photos_all = Home.all
    @tags = Tag.all
  end

  private

  def photo_params
    params.require(:home).permit(:image, :tag_id)
  end
  
end

app/helpers/admin/calenders_helper.rb
module Admin::CalendersHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reserves_helper.rb
module Admin::ReservesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/contacts_helper.rb
module Customer::ContactsHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/plans_helper.rb
module Customer::PlansHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/homes/edit.html.erb
<div class="container mt-5 mb-5 edit-photo">
  
  <h2>写真情報編集</h2>

  <div class="photo-edit">
    <div class="validates">
      <% if @photo.errors.any? %>
        <%= @photo.errors.count %> 件の入力ミスがあります。
        <% @photo.errors.full_messages.each do |message| %><br>
          ・<%= message %>
        <% end %>
      <% end %>
    </div>

    <%= form_with model: @photo, url: admin_home_path, local:true do |f| %>
      <dl>
        <div class="edit-form-group">
          <dt>投稿画像</dt>
          <dd><%= f.attachment_field :image %></dd>
        </div>
        <div class="edit-form-group">
          <dt>タグ</dt>
          <dd><%= f.collection_select :tag_id, Tag.all, :id, :name %></dd>
        </div>
      </dl>

      <div class="form-success">
        <%= f.submit "変更を保存", class:"btn btn-sl btn-dark" %>
      </div>

    <% end %>

    <%= link_to 'Destroy', admin_home_path(@photo.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger admin_home_#{@photo.id} mt-5"%>

  </div>

  <img id="preview" style="width:40%;">

  <script>
    $('#home_image').on('change', function (e) {
      var reader = new FileReader();
      reader.onload = function (e) {
          $("#preview").attr('src', e.target.result);
      }
      reader.readAsDataURL(e.target.files[0]);
    });
  </script>

</div>

app/views/admin/homes/index.html.erb
<div class="container mt-5 mb-5 photographs">

  <h2><%= "写真一覧 （全#{@photos_all.count}件）" %></h2>

  <div class="text-right mb-4">
    <%= link_to "新規投稿", new_admin_home_path, class:"btn btn-sm btn-dark" %>
  </div>

</div>


<div class="container mt-5 mb-5 photographs">

  <div class="row justify-content-center mt-5">
    <% @photos.each do |photo| %>
      <div class="col col-md-4 index-box">
        <%= link_to admin_home_path(photo.id), data: {"turbolinks" => false} do %>
          <%= attachment_image_tag(photo, :image, class: "index-image") %><br>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="text-center">
    <%= paginate @photos %>
  </div>

</div>

app/views/admin/homes/new.html.erb
<div class="container mt-5 mb-5 new-photo">

    <h2>新規写真登録</h2>

    <div class="photo-new">
      <div class="validates">
        <% if @photo.errors.any? %>
          <%= @photo.errors.count %> 件の入力ミスがあります。
          <% @photo.errors.full_messages.each do |message| %><br>
            ・<%= message %>
          <% end %>
        <% end %>
      </div>

      <%= form_with model: @photo, url: admin_homes_path, local: true do |f| %>

        <dl>
          <div class="form-group">
            <dt>投稿画像</dt>
            <dd><%= f.attachment_field :image %></dd>
          </div>
          <div class="form-group">
            <dt>タグ</dt>
            <dd><%= f.collection_select :tag_id, Tag.all, :id, :name, :prompt => "選択してください" %></dd>
          </div>
        </dl>
        
        <div class="form-success">
          <%= f.submit "新規登録", class: "btn btn-sm btn-dark" %>
        </div>

      <% end %>

    </div>

    <img id="preview" style="width:40%;">

    <script>
      $('#home_image').on('change', function (e) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $("#preview").attr('src', e.target.result);
        }
        reader.readAsDataURL(e.target.files[0]);
      });
    </script>

</div>

app/views/admin/homes/show.html.erb
<div class="flash">
	<%= flash[:notice] %>
</div>

<div class="container mt-5 mb-5 show-photo">

	<h2>写真詳細</h2>

  <div class="row">

		<div class="col-md-5">
			<div class="text-center">
				<%= attachment_image_tag(@photo, :image, size: "300x217" ) %>
			</div>
		</div>

		<div class="col-md-6 ml-3">
			<dl>
				<div class="form-group">
					<dt>タグ</dt>
					<dd>・<%= @photo.tag.name %></dd>
				</div>
			</dl>
			<div class="btn-edit mt-5">
				<%= link_to "編集する", edit_admin_home_path(@photo.id), class: "btn btn-sl btn-dark" %>
			</div>
			<div class="btn-new mt-5">
				<%= link_to "新規登録", new_admin_home_path, class: "btn btn-sl btn-dark" %>
			</div>
		</div>

	</div>

</div>