config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions',
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  # 顧客
  root to: "customer/plans#index"
  get "/about" => "customer/homes#about"
  get "/photographs" => "customer/homes#index"

  scope module: :customer do
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get "unsubsclibe"
        patch "withdraw"
      end
    end

    resources :plans, only: [:index, :show, :create] do
      collection do
        get "flow"
        get "bridal"
        get "seizinshiki"
        get "maternity"
        get "child"
        get "trip"
        get "couple"
        get "shichigosan"
        get "friend"
      end
    end

    resources :reserves, except: [:update, :destroy, :edit] do
      collection do
        post "confirm"
        post "back"
        get "complete"
      end
    end

    resources :contacts do
      collection do
        post "confirm"
        post "back"
        get "complete"
      end
    end

    resources :calenders, only: [:index]

    resources :reviews
  end

  # 管理者
  namespace :admin do
    resources :homes
    resources :tags, except: [:show, :new]
    resources :customers, except: [:new, :create, :destroy]
    resources :reserves, only: [:index, :show]
    resources :contacts, except: [:show]
    resources :calenders, except: [:show, :destroy]
    resources :reviews, only: [:index, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # バリデーション
  validates :email, presence: true, uniqueness: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calender.rb
class Calender < ApplicationRecord

  # バリデーション
  validates :start_time, presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord
  
  belongs_to :customers, optional: true

  # バリデーション
  with_options presence: true do
    validates :title
    validates :detail
    validates :title_reply
    validates :detail_reply
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reserves
  has_many :contacts
  has_many :reviews

  # バリデーション
  with_options presence: true do
    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :post_cord, presence: true
    validates :address, presence: true
  end

  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :phone_number, presence: true, numericality: { only_integer: true }
  validates :email, presence: true, uniqueness: true

end

app/models/home.rb
class Home < ApplicationRecord

  attachment :image

  belongs_to :tag

  # バリデーション
  with_options presence: true do
    validates :tag_id
    validates :image
  end

end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/reserve.rb
class Reserve < ApplicationRecord

  belongs_to :customer, optional: true

  # enum設定
  enum plan_name: {
    bridal: 0, seizinshiki: 1, maternity: 2,
    child: 3, trip: 4, couple: 5, shichigosan: 6, friend: 7,
  }

  # バリデーション
  with_options presence: true do
    validates :plan_name
    validates :count
    validates :reserve_day
  end

end

app/models/review.rb
class Review < ApplicationRecord
  
  belongs_to :customers, optional: true

  # enum設定
  enum title: {
    bridal: 0, seizinshiki: 1, maternity: 2,
    child: 3, trip: 4, couple: 5, shichigosan: 6, friend: 7,
  }

  # バリデーション
  with_options presence: true do
    validates :title
    validates :evaluation
    validates :contents
  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :homes

  # バリデーション
  validates :name, presence: true

end

app/controllers/admin/calenders_controller.rb
class Admin::CalendersController < ApplicationController
  before_action :set_beginning_of_week

  def index
    @calenders = Calender.all
  end

  def new
    @calender = Calender.new
  end

  def create
    @calender = Calender.new(calender_params)
    if @calender.save
      redirect_to admin_calenders_path, notice: "スケジュールを追加しました。"
    else
      render "new"
    end
  end

  def edit
    @calender = Calender.find(params[:id])
  end

  def update
    @calender = Calender.find(params[:id])
    if @calender.update(calender_params)
      redirect_to admin_calenders_path, notice: "スケジュールを編集しました"
    else
      render "edit"
    end
  end

  private

  def calender_params
    params.require(:calender).permit(:title, :start_time)
  end

  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end
end

app/controllers/customer/calenders_controller.rb
class Customer::CalendersController < ApplicationController
  before_action :set_beginning_of_week

  def index
    @calenders = Calender.all
  end

  private

  def calender_parameter
    params.require(:calender).permit(:title, :start_at)
  end

  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end
  
end

app/helpers/admin/calenders_helper.rb
module Admin::CalendersHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reserves_helper.rb
module Admin::ReservesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/calenders_helper.rb
module Customer::CalendersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/plans_helper.rb
module Customer::PlansHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/calenders/edit.html.erb
<div class="container mt-5 mb-5 new-carender">

  <h2>スケジュール変更</h2>

  <%= form_with model: @calender, url: admin_calender_path, local: true do |f| %>

    <div class="time mt-5">
      <%= f.label :スケジュール変更日 %><br>
      <%= f.date_field :start_time %>
    </div>

    <div class="title mt-4">
      <%= f.check_box :title, id: :true %>
      <%= f.label :撮影可%>
    </div>

    <div class="submit mt-4">
      <%= f.submit "スケジュール追加", class: "btn btn-sm btn-dark" %>
    </div>

  <% end %>

</div>

app/views/admin/calenders/index.html.erb
<div class="flash">
	<%= flash[:notice] %>
</div>

<div class="container mt-5 mb-5 calender">

  <h2 class="mb-5">撮影可能スケジュール管理</h2>

  <div class="create-schedule text-right">
    <%= link_to new_admin_calender_path, class: "btn btn-dark plus" do %>
      <span class="material-icons md-24">add_box</span>
    <% end %>
  </div>

  <%= month_calendar events: @calenders do |date, calenders| %>
    <%= date.day %>

    <% calenders.each do |calender| %>
      <% if calender.title == true %>
        <%= link_to edit_admin_calender_path(calender), class: 'nav-link text-light  ml-2' do %>
  			  <p class="OK text-center"><strong>撮影可</strong></p>
			  <% end %>
			<% end %>
    <% end %>
  <% end %>

</div>

app/views/admin/calenders/new.html.erb
<div class="container mt-5 mb-5 new-carender">

  <h2>スケジュール管理</h2>
  
  <div class="validates">
    <% if @calender.errors.any? %>
      <%= @calender.errors.count %> 件の入力ミスがあります。
      <% @calender.errors.full_messages.each do |message| %><br>
        ・<%= message %>
      <% end %>
    <% end %>
  </div>

  <%= form_with model: @calender, url: admin_calenders_path, local: true do |f| %>

    <div class="time mt-5">
      <%= f.label :スケジュール変更日 %><br>
      <%= f.date_field :start_time %>
    </div>

    <div class="title mt-4">
      <%= f.check_box :title, id: :true %>
      <%= f.label :撮影可%>
    </div>

    <div class="submit mt-4">
      <%= f.submit "スケジュール追加", class: "btn btn-sm btn-dark" %>
    </div>

  <% end %>

</div>